### ISSUE TITLE
Warnings when generating dSYM with 1.1.0

### ISSUE THREAD

**Issue by IsabellaYeap** [MOLPay/molpay-mobile-xdk-cocoapods#1]
I'm getting several warnings on the "GenerateDSYMFile" step of the build process with warnings such as:

`while processing /Users/Isabellayeap/Desktop/wusify/Vendors/MOLPay/MOLPayXDK.framework/MOLPayXDK(MOLPayWebview.o):
warning: /var/folders/nc/0t0vn2lx38bbpnx4rxp4fhc00000gp/C/org.llvm.clang.clement/ModuleCache/1O56Q6GJJRH39/UIKit-1L3UEFDVKSNO6.pcm: No such file or directory
note: Module debugging should be disabled when shipping static libraries.`

**Actual**: The project produces multiple build warnings relating to the generation of the dSYM.

Thanks.

**Comment by clewlb** [comment]
@IsabellaYeap, it is a known bug at Cordova, please ignore this error. (ref: https://github.com/floatinghotpot/cordova-extension/issues/9)
