### ISSUE TITLE
Hidden MOLPayLib ViewController

### ISSUE THREAD

**Issue by hoangtam101** [MOLPay/molpay-mobile-xdk-cocoapods#2]
I found this bug on my app
Im create ViewController from MOLPayLib and presentation it
some time app go to background mode or pressed home button
MolPayLib call function onAppGoForeground
this is function hidden MolPayLib and navigation controller
now i fixed this issue by way
create sub class MolPayLib override onAppGoForeground function
this bug is fixed.
Thank you.

**Comment by clewlb** [comment]
@hoangtam101,

Could you share with us on how you can reproduce the issue at the onAppGoForeground function, it could help us improve our XDK if you can capture it on video and send it to us at mobile@molpay.com.

Thank you.

**Comment by hoangtam101** [comment]
You can see this bug on youtube link.
Im just reproduce and upload to youtube for you.
https://youtu.be/m8hBrEDFfgk
My Skype: tamh_cntt
Thank you.
