### ISSUE TITLE
error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by sherman-hii** [MOLPay/molpay-mobile-xdk-cocoapods#3]
ld: bitcode bundle could not be generated because 'Pods/MOLPayXDK/MOLPayXDK.framework/MOLPayXDK(MOLPayMainUI.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file 'Pods/MOLPayXDK/MOLPayXDK.framework/MOLPayXDK' for architecture arm64
 molpay pod version 3.14.0

This error only happens when archive.

**Comment by clewlb** [comment]
@sherman-hii,

Please update to our latest version 3.15.0, it fixes this issue.

Thanks for reporting.
